CXX = -std=c++98
CFLAGS = -Wall -Werror -Wextra -pedantic -g
CC = c++ $(CFLAGS) $(CXX) 1

INCL = includes/

SRC_DIR = src/
SRC = ATool.cpp Hammer.cpp main.cpp Shovel.cpp test.cpp Worker.cpp Workshop.cpp

SRC := $(addprefix $(SRC_DIR), $(SRC))

OBJ_DIR = obj/
OBJ = $(SRC:$(SRC_DIR)%.cpp=$(OBJ_DIR)%.o)

# compilation rules

all : ${NAME}

debug : CFLAGS += -DDEBUG_FLAG
debug : re

${NAME} : ${OBJ}
$(CC) $(OBJ) -o $(NAME)

$(OBJ_DIR)%.o : $(SRC_DIR)%.cpp | $(OBJ_DIR)
$(CC) -I${INCL} -c $< -o $@

${OBJ_DIR} :
mkdir -p $@

# clean up

clean :
rm -rf ${OBJ}

fclean : clean
rm -f ${NAME}

re : fclean all

.PHONY: all clean fclean re debug

# read pedantic
# read O3
# wshadow

